language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.0
before_script:
  - dotnet restore
script:  
  - dotnet build ./src/JotFormWebhookParser -c Release -f netcoreapp2.0
  - dotnet test ./tests/JotFormWebhookParser.Tests -c Release -f netcoreapp2.0